### ISSUE TITLE
How can I disable use Firebase

### ISSUE THREAD

**Issue by Firstnsnd** [highlight/highlight#10166]
I deploy highlight in Intranet Environment by deocker-compose as follow:
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: highlight
      POSTGRES_PASSWORD: highlight
      POSTGRES_DB: highlight
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - chdata:/var/lib/clickhouse
  backend:
    image: ghcr.io/highlight/highlight-backend:docker-v0.5.2
    depends_on:
      - postgres
      - redis
      - clickhouse
    environment:
      DATABASE_URL: postgres://highlight:highlight@postgres:5432/highlight?sslmode=disable
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_URL: clickhouse://clickhouse:9000
      FRONTEND_URI: http://localhost:3000
      BACKEND_URI: http://localhost:8082
      DISABLE_AUTH: "true"  
      DISABLE_TELEMETRY: true
      LOG_LEVEL: debug
      OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: "highlight-backend"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      WHITELISTED_FIREBASE_ACCOUNT: "admin@example.com"
      ADMIN_EMAIL: "admin@example.com" 
      ADMIN_PASSWORD: "SecurePassword123!"  
      ADMIN_FULLNAME: "admin"  
    ports:
      - "8082:8082"
  frontend:
    image: ghcr.io/highlight/highlight-frontend:docker-v0.5.2
    depends_on:
      - backend
    environment:
      REACT_APP_FRONTEND_URI: http://localhost:3000
      REACT_APP_PUBLIC_GRAPH_URI: http://localhost:8082/public
      REACT_APP_PRIVATE_GRAPH_URI: http://localhost:8082/private
    ports:
      - "3000:3000"
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
volumes:
  pgdata:
  chdata:
```

when i sign_in get err: `Firebase: The supplied auth credential is incorrect, malformed or has expired. (auth/invalid-credential).`, on my deploy machine,it's can't connect Firebase,so how can i disable use Firebase?
