### ISSUE TITLE
nginx config: `app.highlight.io` is hard coded for hobby deployment and seeing unexpected http redirect

### ISSUE THREAD

**Issue by devcat20** [highlight/highlight#7369]
Thanks for making this amazing project!

**Describe the bug**
When deploy this docker-compose hobby deployment, my frontend is constantly redirected to `https://localhost` rather than my Cloudflare tunnel proxy address.

**To Reproduce**

```
x-depends-infra: &depends-infra
    depends_on:
        kafka:
            condition: service_started
        redis:
            condition: service_started
        postgres:
            condition: service_healthy
        clickhouse:
            condition: service_started
        collector:
            condition: service_started
 
x-backend-env: &backend-env
    environment:
        - CLICKHOUSE_ADDRESS
        - CLICKHOUSE_DATABASE
        - CLICKHOUSE_PASSWORD
        - CLICKHOUSE_USERNAME
        - DEMO_PROJECT_ID
        - DOPPLER_CONFIG
        - ENABLE_OBJECT_STORAGE=true
        - ENVIRONMENT
        - FIREBASE_SECRET
        - FRONTEND_URI
        - IN_DOCKER=true
        - IN_DOCKER_GO=true
        - KAFKA_SERVERS
        - KAFKA_TOPIC
        - OBJECT_STORAGE_FS=/highlight-data
        - ON_PREM=true
        - OTLP_ENDPOINT
        - PSQL_DB
        - PSQL_HOST
        - PSQL_PASSWORD
        - PSQL_PORT
        - PSQL_USER
        - REACT_APP_AUTH_MODE=simple
        - REACT_APP_COMMIT_SHA
        - REACT_APP_FRONTEND_URI
        - REACT_APP_PRIVATE_GRAPH_URI
        - PRIVATE_GRAPH_URI
        - PUBLIC_GRAPH_URI
        - REDIS_ADDRESS
        - REDIS_EVENTS_STAGING_ENDPOINT
        - SESSION_FILE_PATH_PREFIX
        - TZ
        - ADMIN_PASSWORD
 
services:
    kafka:
        extends:
            file: compose.yml
            service: kafka
        environment:
            # needs to share docker-internal address
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
 
    collector:
        extends:
            file: compose.yml
            service: collector
        volumes:
            - ./otel-collector.hobby.yaml:/etc/otel-collector-config.yaml
 
    backend:
        container_name: backend
        image: ghcr.io/highlight/highlight-backend:latest
        healthcheck:
            test: ['CMD', 'curl', '-f', '-k', 'https://localhost:8082/health']
            start_period: 60s
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 38082:8082
        volumes:
            - highlight-data:/highlight-data
        <<: *backend-env
 
    frontend:
        container_name: frontend
        image: ghcr.io/highlight/highlight-frontend:latest
        healthcheck:
            test: ['CMD', 'curl', '-f', '-k', 'https://localhost:3000/']
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 3000:3000
            - 36006:6006
            - 38080:8080
        environment:
            - REACT_APP_PRIVATE_GRAPH_URI
            - REACT_APP_PUBLIC_GRAPH_URI
            - REACT_APP_FRONTEND_URI
    cf-tunnel-fe:
        image: cloudflare/cloudflared:latest
        command: tunnel --no-autoupdate run --url http://frontend:3000 --token $CF_TUNNEL_FE_TOKEN
        restart: unless-stopped
        environment:
            - CF_TUNNEL_FE_TOKEN
    cf-tunnel-be:
        image: cloudflare/cloudflared:latest
        command: tunnel --no-autoupdate run --url http://backend:3000 --token $CF_TUNNEL_BE_TOKEN
        restart: unless-stopped
        environment:
            - CF_TUNNEL_BE_TOKEN
 
volumes:
    highlight-data:
        driver: local
        driver_opts:
            type: none
            device: ./data
            o: bind
```

`.env` is like

```
PRIVATE_GRAPH_URI=https://hl-be.myappdomain.com/private
PUBLIC_GRAPH_URI=https://hl-be.myappdomain.com/public
REACT_APP_PRIVATE_GRAPH_URI=https://hl-be.myappdomain.com/private
REACT_APP_PUBLIC_GRAPH_URI=https://hl-be.myappdomain.com/public
REACT_APP_FRONTEND_URI=https://hl.myappdomain.com
FRONTEND_URI=https://hl.myappdomain.com
 
CF_TUNNEL_FE_TOKEN=
 
CF_TUNNEL_BE_TOKEN=
```

**Expected behavior**

The frontend app should continue to `https://hl.myappdomain.com`

**Screenshots**

**Additional context**
curl:

```
➜ ~ curl https://hl.myappdomain.com -v
* Connected to hl.myappdomain.com (172.64.80.1) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* CAfile: /etc/ssl/cert.pem
* CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
* subject: CN=myappdomain.com
* subjectAltName: host "hl.myappdomain.com" matched cert's "*.myappdomain.com"
* issuer: C=US; O=Let's Encrypt; CN=E1
* SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://hl.myappdomain.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: hl.myappdomain.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: hl.myappdomain.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 307
< content-type: text/html
< location: https://hl.myappdomain.com:3000/
< cf-cache-status: DYNAMIC
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< alt-svc: h3=":443"; ma=86400
<

307 Temporary Redirect

307 Temporary Redirect
======================
* * *

nginx/1.24.0
```
